title: libultraship Documentation
description: >-
  A library providing reimplementations of libultra (N64 SDK) functions
  for modern hardware. Enables PC ports of N64 games.

url: "https://libultraship.com"
baseurl: ""

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

aux_links:
  GitHub: "https://github.com/Kenix3/libultraship"

aux_links_new_tab: true

nav_external_links:
  - title: API Reference
    url: api/index.html
    hide_icon: false

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"

markdown: kramdown
