set(CVAR_VSYNC_ENABLED "gVsyncEnabled" CACHE STRING "")
set(CVAR_Z_FIGHTING_MODE "gZFightingMode" CACHE STRING "")
set(CVAR_NEW_FILE_DROPPED "gNewFileDropped" CACHE STRING "")
set(CVAR_DROPPED_FILE "gDroppedFile" CACHE STRING "")
set(CVAR_INTERNAL_RESOLUTION "gInternalResolution" CACHE STRING "")
set(CVAR_MSAA_VALUE "gMSAAValue" CACHE STRING "")
set(CVAR_SDL_WINDOWED_FULLSCREEN "gSdlWindowedFullscreen" CACHE STRING "")
set(CVAR_TEXTURE_FILTER "gTextureFilter" CACHE STRING "")
set(CVAR_IMGUI_CONTROLLER_NAV "gControlNav" CACHE STRING "")
set(CVAR_CONSOLE_WINDOW_OPEN "gConsoleEnabled" CACHE STRING "")
set(CVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN "gControllerConfigurationEnabled" CACHE STRING "")
set(CVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN "gControllerDisconnectedWindowEnabled" CACHE STRING "")
set(CVAR_CONTROLLER_REORDERING_WINDOW_OPEN "gControllerReorderingWindowEnabled" CACHE STRING "")
set(CVAR_GFX_DEBUGGER_WINDOW_OPEN "gGfxDebuggerEnabled" CACHE STRING "")
set(CVAR_STATS_WINDOW_OPEN "gStatsEnabled" CACHE STRING "")
set(CVAR_ENABLE_MULTI_VIEWPORTS "gEnableMultiViewports" CACHE STRING "")
set(CVAR_LOW_RES_MODE "gLowResMode" CACHE STRING "")
set(CVAR_SIMULATED_INPUT_LAG "gSimulatedInputLag" CACHE STRING "")
set(CVAR_GAME_OVERLAY_FONT "gOverlayFont" CACHE STRING "")
set(CVAR_MENU_BAR_OPEN "gOpenMenuBar" CACHE STRING "")
set(CVAR_PREFIX_CONTROLLERS "gControllers" CACHE STRING "")
set(CVAR_PREFIX_ADVANCED_RESOLUTION "gAdvancedResolution" CACHE STRING "")

set(LUS_BTN_A KbScancode::LUS_KB_X CACHE STRING "")
set(LUS_BTN_B KbScancode::LUS_KB_C CACHE STRING "")
set(LUS_BTN_L KbScancode::LUS_KB_E CACHE STRING "")
set(LUS_BTN_R KbScancode::LUS_KB_R CACHE STRING "")
set(LUS_BTN_Z KbScancode::LUS_KB_Z CACHE STRING "")
set(LUS_BTN_START KbScancode::LUS_KB_SPACE CACHE STRING "")
set(LUS_BTN_STICKUP LUS_KB_W CACHE STRING "")
set(LUS_BTN_STICKDOWN LUS_KB_S CACHE STRING "")
set(LUS_BTN_STICKLEFT LUS_KB_A CACHE STRING "")
set(LUS_BTN_STICKRIGHT LUS_KB_D CACHE STRING "")
set(LUS_BTN_CUP KbScancode::LUS_KB_ARROWKEY_UP CACHE STRING "")
set(LUS_BTN_CDOWN KbScancode::LUS_KB_ARROWKEY_DOWN CACHE STRING "")
set(LUS_BTN_CLEFT KbScancode::LUS_KB_ARROWKEY_LEFT CACHE STRING "")
set(LUS_BTN_CRIGHT KbScancode::LUS_KB_ARROWKEY_RIGHT CACHE STRING "")
set(LUS_BTN_DUP KbScancode::LUS_KB_T CACHE STRING "")
set(LUS_BTN_DDOWN KbScancode::LUS_KB_G CACHE STRING "")
set(LUS_BTN_DLEFT KbScancode::LUS_KB_F CACHE STRING "")
set(LUS_BTN_DRIGHT KbScancode::LUS_KB_H CACHE STRING "")

add_compile_definitions(
	CVAR_VSYNC_ENABLED="${CVAR_VSYNC_ENABLED}"
	CVAR_Z_FIGHTING_MODE="${CVAR_Z_FIGHTING_MODE}"
	CVAR_NEW_FILE_DROPPED="${CVAR_NEW_FILE_DROPPED}"
	CVAR_DROPPED_FILE="${CVAR_DROPPED_FILE}"
	CVAR_INTERNAL_RESOLUTION="${CVAR_INTERNAL_RESOLUTION}"
	CVAR_MSAA_VALUE="${CVAR_MSAA_VALUE}"
	CVAR_SDL_WINDOWED_FULLSCREEN="${CVAR_SDL_WINDOWED_FULLSCREEN}"
	CVAR_TEXTURE_FILTER="${CVAR_TEXTURE_FILTER}"
	CVAR_IMGUI_CONTROLLER_NAV="${CVAR_IMGUI_CONTROLLER_NAV}"
	CVAR_CONSOLE_WINDOW_OPEN="${CVAR_CONSOLE_WINDOW_OPEN}"
	CVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN="${CVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN}"
	CVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN="${CVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN}"
	CVAR_CONTROLLER_REORDERING_WINDOW_OPEN="${CVAR_CONTROLLER_REORDERING_WINDOW_OPEN}"
	CVAR_GFX_DEBUGGER_WINDOW_OPEN="${CVAR_GFX_DEBUGGER_WINDOW_OPEN}"
	CVAR_STATS_WINDOW_OPEN="${CVAR_STATS_WINDOW_OPEN}"
	CVAR_ENABLE_MULTI_VIEWPORTS="${CVAR_ENABLE_MULTI_VIEWPORTS}"
	CVAR_LOW_RES_MODE="${CVAR_LOW_RES_MODE}"
	CVAR_SIMULATED_INPUT_LAG="${CVAR_SIMULATED_INPUT_LAG}"
	CVAR_GAME_OVERLAY_FONT="${CVAR_GAME_OVERLAY_FONT}"
	CVAR_MENU_BAR_OPEN="${CVAR_MENU_BAR_OPEN}"
	CVAR_PREFIX_CONTROLLERS="${CVAR_PREFIX_CONTROLLERS}"
	CVAR_PREFIX_ADVANCED_RESOLUTION="${CVAR_PREFIX_ADVANCED_RESOLUTION}"

	LUS_BTN_A=${LUS_BTN_A}
	LUS_BTN_B=${LUS_BTN_B}
	LUS_BTN_L=${LUS_BTN_L}
	LUS_BTN_R=${LUS_BTN_R}
	LUS_BTN_Z=${LUS_BTN_Z}
	LUS_BTN_START=${LUS_BTN_START}
	LUS_BTN_STICKUP=${LUS_BTN_STICKUP}
	LUS_BTN_STICKDOWN=${LUS_BTN_STICKDOWN}
	LUS_BTN_STICKLEFT=${LUS_BTN_STICKLEFT}
	LUS_BTN_STICKRIGHT=${LUS_BTN_STICKRIGHT}
	LUS_BTN_CUP=${LUS_BTN_CUP}
	LUS_BTN_CDOWN=${LUS_BTN_CDOWN}
	LUS_BTN_CLEFT=${LUS_BTN_CLEFT}
	LUS_BTN_CRIGHT=${LUS_BTN_CRIGHT}
	LUS_BTN_DUP=${LUS_BTN_DUP}
	LUS_BTN_DDOWN=${LUS_BTN_DDOWN}
	LUS_BTN_DLEFT=${LUS_BTN_DLEFT}
	LUS_BTN_DRIGHT=${LUS_BTN_DRIGHT}
)
