set(CVAR_VSYNC_ENABLED "gVsyncEnabled" CACHE STRING "")
set(CVAR_Z_FIGHTING_MODE "gZFightingMode" CACHE STRING "")
set(CVAR_NEW_FILE_DROPPED "gNewFileDropped" CACHE STRING "")
set(CVAR_DROPPED_FILE "gDroppedFile" CACHE STRING "")
set(CVAR_INTERNAL_RESOLUTION "gInternalResolution" CACHE STRING "")
set(CVAR_MSAA_VALUE "gMSAAValue" CACHE STRING "")
set(CVAR_SDL_WINDOWED_FULLSCREEN "gSdlWindowedFullscreen" CACHE STRING "")
set(CVAR_TEXTURE_FILTER "gTextureFilter" CACHE STRING "")
set(CVAR_CONTROL_NAV "gControlNav" CACHE STRING "")
set(CVAR_CONSOLE_ENABLED "gConsoleEnabled" CACHE STRING "")
set(CVAR_CONTROLLER_CONFIGURATION_ENABLED "gControllerConfigurationEnabled" CACHE STRING "")
set(CVAR_CONTROLLER_DISCONNECTED_ENABLED "gControllerDisconnectedWindowEnabled" CACHE STRING "")
set(CVAR_CONTROLLER_REORDERING_ENABLED "gControllerReorderingWindowEnabled" CACHE STRING "")
set(CVAR_GFX_DEBUGGER_ENABLED "gGfxDebuggerEnabled" CACHE STRING "")
set(CVAR_STATS_ENABLED "gStatsEnabled" CACHE STRING "")
set(CVAR_ENABLE_MULTI_VIEWPORTS "gEnableMultiViewports" CACHE STRING "")
set(CVAR_LOW_RES_MODE "gLowResMode" CACHE STRING "")
set(CVAR_SIMULATED_INPUT_LAG "gSimulatedInputLag" CACHE STRING "")
set(CVAR_ALT_ASSETS "gAltAssets" CACHE STRING "")
set(CVAR_SINK_ENABLED "gSinkEnabled" CACHE STRING "")
set(CVAR_GAME_OVERLAY_FONT "gOverlayFont" CACHE STRING "")
set(CVAR_OPEN_MENU_BAR "gOpenMenuBar" CACHE STRING "")
set(CVAR_BLOCK_CONTROLLERS "gControllers" CACHE STRING "")
set(CVAR_BLOCK_ADVANCED_RESOLUTION "gAdvancedResolution" CACHE STRING "")
add_compile_definitions(
	CVAR_VSYNC_ENABLED="${CVAR_VSYNC_ENABLED}"
	CVAR_Z_FIGHTING_MODE="${CVAR_Z_FIGHTING_MODE}"
	CVAR_NEW_FILE_DROPPED="${CVAR_NEW_FILE_DROPPED}"
	CVAR_DROPPED_FILE="${CVAR_DROPPED_FILE}"
	CVAR_INTERNAL_RESOLUTION="${CVAR_INTERNAL_RESOLUTION}"
	CVAR_MSAA_VALUE="${CVAR_MSAA_VALUE}"
	CVAR_SDL_WINDOWED_FULLSCREEN="${CVAR_SDL_WINDOWED_FULLSCREEN}"
	CVAR_TEXTURE_FILTER="${CVAR_TEXTURE_FILTER}"
	CVAR_CONTROL_NAV="${CVAR_CONTROL_NAV}"
	CVAR_CONSOLE_ENABLED="${CVAR_CONSOLE_ENABLED}"
	CVAR_CONTROLLER_CONFIGURATION_ENABLED="${CVAR_CONTROLLER_CONFIGURATION_ENABLED}"
	CVAR_CONTROLLER_DISCONNECTED_ENABLED="${CVAR_CONTROLLER_DISCONNECTED_ENABLED}"
	CVAR_CONTROLLER_REORDERING_ENABLED="${CVAR_CONTROLLER_REORDERING_ENABLED}"
	CVAR_GFX_DEBUGGER_ENABLED="${CVAR_GFX_DEBUGGER_ENABLED}"
	CVAR_STATS_ENABLED="${CVAR_STATS_ENABLED}"
	CVAR_ENABLE_MULTI_VIEWPORTS="${CVAR_ENABLE_MULTI_VIEWPORTS}"
	CVAR_LOW_RES_MODE="${CVAR_LOW_RES_MODE}"
	CVAR_SIMULATED_INPUT_LAG="${CVAR_SIMULATED_INPUT_LAG}"
	CVAR_ALT_ASSETS="${CVAR_ALT_ASSETS}"
	CVAR_SINK_ENABLED="${CVAR_SINK_ENABLED}"
	CVAR_GAME_OVERLAY_FONT="${CVAR_GAME_OVERLAY_FONT}"
	CVAR_OPEN_MENU_BAR="${CVAR_OPEN_MENU_BAR}"
	CVAR_BLOCK_CONTROLLERS="${CVAR_BLOCK_CONTROLLERS}"
	CVAR_BLOCK_ADVANCED_RESOLUTION="${CVAR_BLOCK_ADVANCED_RESOLUTION}"
)