@prism(type='glsl', name='Fast3D Vulkan Vertex Shader', version='1.0.0', description='Vulkan shader generated by prism', author='Shipwright Team')

#version 450

layout(location = 0) in vec4 aVtxPos;

@for(i in 0..2)
    @if(o_textures[i])
        layout(location = @{next_attrib_location(2)}) in vec2 aTexCoord@{i};
        layout(location = @{next_varying_location()}) out vec2 vTexCoord@{i};
        @for(j in 0..2)
            @if(o_clamp[i][j])
                @if(j == 0)
                    layout(location = @{next_attrib_location(1)}) in float aTexClampS@{i};
                    layout(location = @{next_varying_location()}) out float vTexClampS@{i};
                @else
                    layout(location = @{next_attrib_location(1)}) in float aTexClampT@{i};
                    layout(location = @{next_varying_location()}) out float vTexClampT@{i};
                @end
            @end
        @end
    @end
@end

@if(o_fog)
layout(location = @{next_attrib_location(4)}) in vec4 aFog;
layout(location = @{next_varying_location()}) out vec4 vFog;
@end

@if(o_grayscale)
layout(location = @{next_attrib_location(4)}) in vec4 aGrayscaleColor;
layout(location = @{next_varying_location()}) out vec4 vGrayscaleColor;
@end

@for(i in 0..o_inputs)
    @if(o_alpha)
        layout(location = @{next_attrib_location(4)}) in vec4 aInput@{i + 1};
        layout(location = @{next_varying_location()}) out vec4 vInput@{i + 1};
    @else
        layout(location = @{next_attrib_location(3)}) in vec3 aInput@{i + 1};
        layout(location = @{next_varying_location()}) out vec3 vInput@{i + 1};
    @end
@end

void main() {
    @for(i in 0..2)
        @if(o_textures[i])
            vTexCoord@{i} = aTexCoord@{i};
            @for(j in 0..2)
                @if(o_clamp[i][j])
                    @if(j == 0)
                        vTexClampS@{i} = aTexClampS@{i};
                    @else
                        vTexClampT@{i} = aTexClampT@{i};
                    @end
                @end
            @end
        @end
    @end

    @if(o_fog)
        vFog = aFog;
    @end
    @if(o_grayscale)
        vGrayscaleColor = aGrayscaleColor;
    @end
    @for(i in 0..o_inputs)
        vInput@{i + 1} = aInput@{i + 1};
    @end

    gl_Position = aVtxPos;
}
